# Generated by Django 5.2.8 on 2026-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermastermodel',
            name='account_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'create'), (1, 'review'), (2, 'block'), (3, 'delete')], default=0),
        ),
    ]
