# Generated by Django 5.2.8 on 2026-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic_service', '0002_usermastermodel_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomermodel',
            name='sex',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermastermodel',
            name='age',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermastermodel',
            name='sex',
            field=models.SmallIntegerField(),
        ),
    ]
