# Generated by Django 5.2.8 on 2026-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic_service', '0003_alter_usercustomermodel_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomermodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
