# Generated by Django 5.2.8 on 2026-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('openid', models.CharField(max_length=32, unique=True)),
                ('access_token', models.CharField(max_length=128)),
                ('token_expired', models.DateTimeField()),
                ('nickname', models.CharField(default='', max_length=64)),
                ('sex', models.IntegerField(choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(default='')),
                ('account_status', models.IntegerField(choices=[(0, 'created'), (1, 'blocking'), (2, 'deleted')], default=0)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customer',
                'db_table': 'user_customer',
            },
        ),
    ]
