# Generated by Django 5.2.8 on 2026-03-19 08:49

import app_base_service.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('openid', models.CharField(max_length=32, unique=True)),
                ('access_token', models.CharField(max_length=128)),
                ('token_expired', models.DateTimeField()),
                ('sex', models.SmallIntegerField(blank=True, choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0)),
                ('age', models.SmallIntegerField(blank=True, default=0)),
                ('phone', models.CharField(max_length=11)),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.TextField(blank=True, default='', max_length=256)),
                ('account_status', models.SmallIntegerField(blank=True, choices=[(0, 'create'), (1, 'block'), (2, 'delete')], default=0)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customer',
                'db_table': 'user_customer',
            },
        ),
        migrations.CreateModel(
            name='UserMasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=64)),
                ('avatar', models.ImageField(upload_to=app_base_service.models.UserMasterModel.upload_avator_file)),
                ('idcard_front', models.ImageField(upload_to=app_base_service.models.UserMasterModel.upload_idcard_font_file)),
                ('idcard_back', models.ImageField(upload_to=app_base_service.models.UserMasterModel.upload_idcard_back_file)),
                ('business_license', models.ImageField(upload_to=app_base_service.models.UserMasterModel.upload_business_license_file)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=256)),
                ('work_year', models.SmallIntegerField()),
                ('level', models.SmallIntegerField(blank=True, default=0)),
                ('user_grade', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2)),
            ],
            options={
                'verbose_name': 'master',
                'verbose_name_plural': 'master',
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='RepairOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=12)),
                ('location', models.TextField(max_length=256)),
                ('repair_category', models.SmallIntegerField(choices=[(0, '维修电动车')])),
                ('contact_phone', models.CharField(max_length=11)),
                ('issue_description', models.TextField(max_length=4096)),
                ('appointment_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('transaction_type', models.SmallIntegerField(blank=True, choices=[(0, '网络支付')], default=0)),
                ('order_status', models.SmallIntegerField(blank=True, choices=[(0, 'create'), (1, 'cancel'), (2, 'delete')], default=0)),
                ('comment', models.TextField(blank=True, default='', max_length=1024)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_base_service.usercustomermodel')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_base_service.usermastermodel')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'repair_order',
            },
        ),
    ]
