# Generated by Django 5.2.8 on 2026-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomermodel',
            name='account_status',
            field=models.IntegerField(blank=True, choices=[(0, 'created'), (1, 'blocking'), (2, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0),
        ),
    ]
