# Generated by Django 5.2.8 on 2026-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base_service', '0002_alter_usercustomermodel_account_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=64)),
                ('avatar', models.ImageField(upload_to='')),
                ('idcard_front', models.ImageField(upload_to='')),
                ('idcard_back', models.ImageField(upload_to='')),
                ('business_license', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=256)),
                ('work_year', models.SmallIntegerField()),
                ('level', models.SmallIntegerField(blank=True, default=0)),
                ('user_grade', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2)),
            ],
            options={
                'verbose_name': 'master',
                'verbose_name_plural': 'master',
                'db_table': 'user_master',
            },
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='account_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'created'), (1, 'blocking'), (2, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='address',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='age',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usercustomermodel',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0),
        ),
    ]
