# Generated by Django 5.2.8 on 2026-03-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base_service', '0003_usermaster_alter_usercustomermodel_account_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMaster',
            new_name='UserMasterModel',
        ),
    ]
