# Generated by Django 5.2.8 on 2025-11-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('user_type', models.IntegerField(choices=[(1, 'customer'), (2, 'master'), (3, 'admin')])),
            ],
        ),
    ]
